# Generated by Django 5.1.3 on 2025-06-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salachat',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre'),
        ),
    ]
