# Generated by Django 5.1.3 on 2025-06-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica1', '0006_usuario_es_vendedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
